### ISSUE TITLE
Doesnt seem to be sending any keypresses?

### ISSUE THREAD

**Issue by zenithex** [Axadiw/MFIGamepadFeeder#20]
So I'm trying to get the controller to work for some time now, but I cant seem to get it. It is paired via bluetooth, with Vendor ID:273, Product ID 5152, the same as the guide. In the mapping editor preview I can see the numbers changing, but it wont send any key presses to vjoy. I've attached a screenshot of the error messages and the preview windows with a couple of buttons held down. I'd really appreciate any help with this, Thanks a million x

http://imgur.com/a/lU4Vl

**Comment by Axadiw** [comment]
Have you installed correct version of the MFIGamepadFeeder for your system? (maybe you're using 32bit instead of 64bit).

Have you rebooted your computer after installation?

If so, could you lauch your command prompt with admin privileges, enter `scp` directory in MFIGamepadFeeder installation path and launch

```
devcon.exe remove Root\ScpVBus
devcon.exe install ScpVBus.inf Root\ScpVBus
```

Reboot computer again, and than check if MFIGamepadFeeder is working correctly?
