### ISSUE TITLE
SteelSeries Stratus Support

### ISSUE THREAD

**Issue by seanmcnally98** [Axadiw/MFIGamepadFeeder#8]
Hey there, found your app, looks awesome.  I see that it was made for the Steelseries Nimbus, which is iOS only.  I haven't gotten it to work with the Steelseries Stratus (the little one, not the XL made for PCs).  It's the only small-form device steelseries offers with double shoulder buttons, and seeing as you're a fan of steelseries products, I was wondering if you'd consider supporting it.  Sorry if this wasn't the proper channel to make this request!

**Comment by Axadiw** [comment]
Unfortunately I don't have Stratus, so I cannot add support for it on my own.

Currently I'm working on new version of the app that will have an option to create profiles for various gamepads.

By the way - have you tried to use the current version of the app with SteelSeries Stratus? How does it work? Are the buttons on the gamepad recognized incorrectly, or it doesn't work at all?

**Comment by seanmcnally98** [comment]
Sorry for the late reply, but yes, I'm using the current version.  The app recognizes the controller when I can get it to connect via Bluetooth to my computer (which is a challenge in itself), but it doesn't recieve any input from it.

**Comment by Lohengramm512** [comment]
Hello and thank you for creating this program. I am also trying to use it to pair a Stratus to my PC. I have a 3.5 year old daughter who has very little hands and can't hold full size controllers, but she already loves playing games with me. I bought the Stratus hoping I could tweak your program to work with it since they are both Steelseries MFI pads. Since it does not work I have 2 options, either I can mail the Stratus back to Amazon for a refund, or I could mail it to you since you stated not having one is a reason you haven't developed support for it.

If I were to mail you my Stratus would you use it to create support / a profile for the controller and mail the device back to me once you are finished testing? It is very tiny and I don't mind paying for shipping both ways wherever you live.

Thank you again for your work. If you do not respond to this message before 1 week has passed I will mail the device back to Amazon for a refund.

**Comment by Axadiw** [comment]
I guess Stratus doesn't support HID mode that is required for MFIGamepadFeeder.
